#!/bin/sh

# This script can be used for running ibis applications with prun (which
# probably is only available on our own DAS system).

# Check if user forgot no-panda flag. In that case, filter rank and nhosts.
NHOSTS=`echo $PRUN_HOSTNAMES | awk '{print NF}'`
case "X${1}X$2" in
X${PRUN_CPU_RANK}X$NHOSTS)
    shift
    shift
    ;;
esac

echo I am `hostname`

# export LD_PRELOAD=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75.x86_64/jre/lib/amd64/libjsig.so

mkdir -p /local/$USER

# with ib, with mem barriers
java -classpath $CLASSPATH \
     -Dibis.io.buffer.size=65536 \
     -Dibis.io.conversion.buffer.size=65536 \
     -XX:+UseMembar \
     -Dcom.sun.management.jmxremote=true \
     -Dcom.sun.management.jmxremote.ssl=false \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Dcom.sun.management.jmxremote.port=14123 \
     -Djava.rmi.server.hostname=localhost \
     -Dcom.sun.management.jmxremote.rmi.port=14124 \
     -Dcom.sun.management.jmxremote.local.only=false \
     -Djava.io.tmpdir=/local/$USER -Dibis.implementation=tcp \
     -Dibis.constellation.queue.limit=0 \
     -Dibis.constellation.profile=true \
     -Dibis.constellation.profile.output=gantt \
     -Dibis.constellation.remotesteal.throttle=true \
     -Dlog4j.configuration=file:"$PRALINE_CASHMERE_DIR"/log4j.properties \
     -Dcashmere.asyncReads=true -Dcashmere.nGlobalExecutors=1 \
     -Dcashmere.nLocalExecutors=4 "$@" 2>&1 | tee out.${PRUN_CPU_RANK}
